/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Logon: typeof import('./components/logon/Logon.vue')['default']
    LogonWrap: typeof import('./components/logon/LogonWrap.vue')['default']
    MessageBox: typeof import('./components/message/MessageBox.vue')['default']
    MessageChild: typeof import('./components/message/MessageChild.vue')['default']
    MessageContent: typeof import('./components/message/MessageContent.vue')['default']
    Register: typeof import('./components/logon/Register.vue')['default']
    ReleaseMessage: typeof import('./components/message/ReleaseMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
